### ISSUE TITLE
No Release file for `impish`

### ISSUE THREAD

**Issue by canadaduane** [deafmute1/deb-pkg-git#3]
When I try to add the ppa (`sudo add-apt-repository ppa:deafmute/interception`), I get the following on Pop!_OS 21.10 (Ubuntu-based):

```
Reading package lists... Done                
E: The repository 'http://ppa.launchpad.net/deafmute/interception/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
I think it's looking for verification that it's compatible with the Ubuntu 21.10 `impish` release?

**Comment by deafmute1** [comment]
I've just copied the existing packages (originally built for groovy) to impish, hirsuit and jammy. They should, as far as I'm aware, work. Please report back if there's any further issues.

**Comment by canadaduane** [comment]
Awesome, thanks!
